version: '3'
services:
  jenkins:
    container_name: ajc-group4-jenkins
    image: mhenniby/ajc-group4-jenkins:1.0
    restart: always
    ports:
      - '8080:8080'
      - '22000:22'
      - '50000:50000'
    volumes:
      - 'jenkins_home:/var/lib/jenkins/'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
volumes:
  jenkins_home:
    driver: local