---
# dev.yaml

all:
  children:
    server:
      hosts:
        ansible:
          ansible_host: 18.218.41.5
    dev:
      hosts:
        client1:
          ansible_host: 3.143.157.46
        client2:
          ansible_host: 3.140.115.244
